name: ClearChat
version: 2.0
author: iXalazar_
main: General.Core.Main
description: Ningun comentario en espacial :) 
commands:
  clearchat:
    aliases: [cc]
























